var PROJECTS = {
  'ethos': {
    tags: ['design', 'motion'],
    categoryLabel: 'Design',
    title: 'Ethos',
    deliverable: 'Performance Marketing Concepts',
    challenge: 'Create performance marketing assets for life insurance on social — a category most people actively avoid thinking about — that stop the scroll and drive action.',
    solution: 'Three static concepts targeting different buyer objections: Price Over Time (cost urgency), Fixed Cost Q&A (rate certainty), and Seamless Online Access (frictionless sign-up).',
    logic: 'Each concept anchors to a distinct reason-to-buy without overlapping. Together they give media buyers options to test against different audience segments.',
    imageNote: '* Images are for reference only and used as a proof of concept. Photos sourced from jakestangel.com',
    motionSection: {
      intro: 'I designed and animated two motion concepts for Ethos\' performance marketing efforts.',
      concepts: [
        {
          title: 'Bouncing Coins — Affordability Message',
          body: 'This concept uses dynamic motion to engage viewers with real-world physics. Four quarters bounce around the screen, reinforcing the affordability of Ethos term life insurance, which costs less than $1 a day. The movement builds curiosity and keeps attention on the message.',
        },
        {
          title: 'UGC Story — Breaking the Taboo',
          body: 'This piece repurposes user-generated content to create a narrative around overcoming discomfort in discussing life insurance. The animation enhances the creator\'s message, making the topic more approachable and encouraging open conversations.',
        },
      ],
    },
    shortDescription: 'Performance marketing concepts for Ethos life insurance — static design and motion.',
    color: '#2c5f3f',
    images: [
      'images/ethos/frame-1.jpg',
      'images/ethos/frame-2.jpg',
      'images/ethos/frame-3.jpg',
      'images/ethos/frame-4.jpg',
    ],
    videos: [
      { id: '1069408293', title: 'Ethos — Bouncing Coins', ratio: '4/5' },
      { id: '1069408320', title: 'UGC — Taboo Topic', ratio: '4/5' },
      { id: '1069408280', title: 'Ethos — Concept', ratio: '9/16' },
      { id: '1069408307', title: 'UGC — Taboo Topic (Alt)', ratio: '9/16' },
    ],
  },
  'spectrum-sportsnet': {
    tags: ['motion', 'design'],
    categoryLabel: 'Broadcast Design',
    title: 'Spectrum Sportsnet',
    deliverable: 'Show Packages & Broadcast Design',
    challenge: 'Build a cohesive visual identity system across multiple LA sports teams — Lakers, Dodgers, Galaxy, and Sparks — that works live on air and adapts to every format.',
    solution: 'Designed show packages, broadcast elements, in-studio visuals, and promotional spots over two years. Key work includes the Inside Access opening sequence built in Cinema 4D.',
    logic: 'Consistent motion language and type system across teams let editors pull from a shared toolkit without losing team-specific identity.',
    color: '#4B2E83',
    images: [
      'images/spectrum-sportsnet/frame-1.jpg',
      'images/spectrum-sportsnet/frame-2.jpg',
      'images/spectrum-sportsnet/frame-3.jpg',
      'images/spectrum-sportsnet/frame-4.jpg',
    ],
    videos: [
      { id: '114083982', ratio: '16/9' },
      { id: '215752741', ratio: '16/9' },
      { id: '122374693', ratio: '16/9' },
    ],
  },
  'high-and-tight': {
    tags: ['motion', 'design'],
    categoryLabel: 'Broadcast Design',
    title: 'High and Tight',
    deliverable: 'Segment Visual Identity',
    challenge: 'Create a visual identity for a Dodgers baseball analysis segment that captures the precision and energy of the sport.',
    solution: 'Designed a bold, kinetic look pulling from baseball\'s graphic tradition — clean lines, sharp cuts, and a color palette anchored in Dodger blue.',
    logic: 'The segment needed to feel distinct within the Spectrum Sportsnet system while clearly belonging to it. Strong typography and motion cues carry the brand.',
    color: '#005A9C',
    images: [
      'images/high-and-tight/frame-1.jpg',
      'images/high-and-tight/frame-2.jpg',
      'images/high-and-tight/frame-3.jpg',
    ],
    videos: [
      { id: '212961179', ratio: '16/9' },
    ],
  },
  'hometowncall': {
    tags: ['motion', 'design'],
    categoryLabel: 'Broadcast Design',
    title: 'Hometown Call',
    deliverable: 'Segment Open',
    challenge: 'Design an opening sequence for a Dodgers coverage segment that feels local and personal — rooted in LA.',
    solution: 'Built a motion package with a warm, editorial feel using found photography and bold typography to ground the segment in the city.',
    logic: 'Spectrum Sportsnet needed segments that could stand on their own tonally. Hometown Call leans warmer and more nostalgic than the harder-edged game coverage.',
    color: '#1A3B6E',
    images: [
      'images/hometowncall/frame-1.jpg',
    ],
    videos: [
      { id: '212959149', ratio: '16/9' },
    ],
  },
  'afterearth': {
    tags: ['motion'],
    categoryLabel: 'Title Design',
    title: 'After Earth',
    deliverable: 'End Title Sequence',
    challenge: 'Design an end title sequence for a major feature film that sustains visual engagement across the full credits roll while matching the film\'s dramatic, atmospheric tone.',
    solution: 'Created an organic motion system using particle simulations and environmental textures — echoing the film\'s themes of nature and survival without replicating the film\'s footage.',
    logic: 'End titles are often treated as an afterthought. The goal was to create something that felt like a natural extension of the film rather than a corporate card.',
    color: '#1C2E1A',
    images: [
      'images/afterearth/frame-1.jpg',
      'images/afterearth/frame-2.jpg',
      'images/afterearth/frame-3.jpg',
      'images/afterearth/frame-4.jpg',
      'images/afterearth/frame-5.jpg',
      'images/afterearth/frame-6.jpg',
      'images/afterearth/frame-7.jpg',
      'images/afterearth/frame-8.jpg',
    ],
    videos: [
      { id: '98816848', ratio: '16/9' },
    ],
  },
  'taco-bell-broadcast': {
    tags: ['motion', 'design'],
    categoryLabel: 'Broadcast',
    title: 'Taco Bell\nBroadcast',
    deliverable: 'Nine Broadcast Spots',
    challenge: 'As Design Director of Food at Deutsch LA, lead the visual language for nine national broadcast spots — each with its own creative concept but needing to feel unified as a campaign.',
    solution: 'Developed a consistent food-forward motion system that could stretch from surreal (Beyond Imagination) to grounded (Undivided Attention) across all nine spots.',
    logic: 'Food design at broadcast scale means every frame has to make the product look irresistible. Lighting, motion, and pacing all serve that single goal.',
    color: '#702082',
    videos: [
      { id: '433650503', ratio: '16/9' },
      { id: '433660304', ratio: '16/9' },
      { id: '433697527', ratio: '16/9' },
      { id: '433702569', ratio: '16/9' },
      { id: '433705718', ratio: '16/9' },
      { id: '433707053', ratio: '16/9' },
      { id: '433740125', ratio: '16/9' },
      { id: '433741665', ratio: '16/9' },
      { id: '433746272', ratio: '16/9' },
    ],
  },

  'noom': {
    tags: ['motion', 'design'],
    categoryLabel: 'Brand & Performance',
    title: 'Noom',
    deliverable: 'Broadcast, Performance Marketing & Product Animation',
    challenge: 'Over two years, produce hundreds of video assets across broadcast campaigns, performance marketing, and product animation — all under one consistent brand voice.',
    solution: 'Led motion design across six broadcast segments (YOUnique), hundreds of Facebook/Instagram performance variants, Lottie animations for web and app, and chatbot motion systems.',
    logic: 'At Noom\'s scale, every asset needs to work independently and feel part of the same system. A shared motion language across formats kept the brand coherent without slowing production.',
    color: '#2B6B3E',
    videos: [
      { id: '916007265', ratio: '16/9' },
      { id: '1056911606', ratio: '16/9' },
      { id: '995510989', ratio: '16/9' },
      { id: '995518821', ratio: '16/9' },
      { id: '1056587488', ratio: '16/9' },
      { id: '1056587500', ratio: '4/5' },
    ],
  },
  'animated-logos': {
    tags: ['motion', 'design'],
    categoryLabel: 'Motion Design',
    title: 'Animated Logos',
    deliverable: 'Logo Animation',
    challenge: 'Translate two distinct brand identities into logo animations — one kinetic and abstract, one architectural and precise — each with its own motion logic.',
    solution: 'Dynamic uses a helix animation to convey energy and transformation. Beacon Capital uses a scripted dotted-to-solid stroke effect that mimics architectural drafting.',
    logic: 'Logo animation should feel like a natural extension of the brand — not just a reveal. Both concepts were designed to feel inevitable for their respective identities.',
    color: '#1a1a2e',
    videos: [
      { id: '1056590766', ratio: '16/9' },
      { id: '1056591037', ratio: '16/9' },
    ],
  },
  'athletic-greens': {
    tags: ['motion'],
    categoryLabel: 'Brand Video',
    title: 'Athletic Greens',
    deliverable: 'Internal Sizzle Reel',
    challenge: 'Produce a compelling internal sizzle reel in one week combining voiceover, action photography, product shots, and tabletop footage.',
    solution: 'Worked with an editor and audio engineer to cut a fast-paced brand video using the owner\'s script as the narrative backbone.',
    logic: 'Tight deadline meant every decision had to serve the cut. The reel needed to communicate product quality and brand energy without wasting a frame.',
    color: '#2D7D3A',
    videos: [
      { id: '1001825990', ratio: '16/9' },
    ],
  },
  'taco-bell-organic-social': {
    tags: ['design', 'motion'],
    categoryLabel: 'Social Content',
    title: 'Taco Bell\nOrganic Social',
    deliverable: 'Three Social Campaigns',
    challenge: 'Design scroll-stopping social content across three distinct campaigns — Party Packs, Vegetarian, and Delivery — each with its own visual identity and platform requirements.',
    solution: 'Party Packs used flash photography and instant film aesthetics. Vegetarian used vibrant plating with kaleidoscope effects. Delivery placed Taco Bell in grounded everyday scenes. Each campaign produced assets for 1:1, 16:9, and 9:16 formats.',
    logic: 'Social content at this scale requires a system, not a series of one-offs. Each campaign had defined visual rules that let the team produce variants without losing coherence.',
    color: '#702082',
    images: [
      'images/taco-bell-organic-social/frame-1.jpg',
      'images/taco-bell-organic-social/frame-2.jpg',
      'images/taco-bell-organic-social/frame-3.jpg',
      'images/taco-bell-organic-social/frame-4.jpg',
      'images/taco-bell-organic-social/frame-5.jpg',
      'images/taco-bell-organic-social/frame-6.jpg',
      'images/taco-bell-organic-social/frame-7.jpg',
      'images/taco-bell-organic-social/frame-8.jpg',
      'images/taco-bell-organic-social/frame-9.jpg',
      'images/taco-bell-organic-social/frame-10.jpg',
      'images/taco-bell-organic-social/frame-11.jpg',
      'images/taco-bell-organic-social/frame-12.jpg',
      'images/taco-bell-organic-social/frame-13.jpg',
      'images/taco-bell-organic-social/frame-14.jpg',
      'images/taco-bell-organic-social/frame-15.jpg',
    ],
    videos: [
      { id: '378049810', ratio: '1/1' },
      { id: '378049827', ratio: '1/1' },
      { id: '378049794', ratio: '1/1' },
      { id: '378049779', ratio: '1/1' },
    ],
  },
  'beats-by-dre-pop': {
    tags: ['motion', 'design'],
    categoryLabel: 'Brand Campaign',
    title: 'Beats by Dre\nPop',
    deliverable: 'Global Campaign — Animation & Design',
    challenge: 'Create animation and design for a global Beats campaign celebrating colorful headphones. The brief: life\'s more fun in color.',
    solution: 'Developed a vibrant motion system using illustration, abstract animation, and color theory. Music by MNEK feat. Hailee Steinfeld drove the pacing and energy.',
    logic: 'The campaign needed to feel joyful and unapologetically bold — motion that matched the product\'s personality rather than just showcasing it.',
    color: '#C41E7A',
    images: [
      'images/beats-by-dre-pop/frame-1.jpg',
      'images/beats-by-dre-pop/frame-2.jpg',
      'images/beats-by-dre-pop/frame-3.jpg',
      'images/beats-by-dre-pop/frame-4.jpg',
      'images/beats-by-dre-pop/frame-5.jpg',
    ],
    videos: [
      { id: '273924404', ratio: '16/9' },
    ],
  },
  'beats-buddy': {
    tags: ['motion'],
    categoryLabel: 'Social Motion',
    title: 'Beats Buddy',
    deliverable: 'Instagram Story Animation',
    challenge: 'Design a motion piece for Instagram Story format promoting Harlan & Alondra\'s album Buddy for the Beats by Dre social team.',
    solution: 'Created a vertical motion design at Laundry Service that matched the album\'s energy and the constraints of the Story format — looping, immediate, and built for sound-off viewing.',
    logic: 'Portrait format social video demands a different motion logic than broadcast. Every element had to read clearly in the first second.',
    color: '#1a1a1a',
    videos: [
      { id: '432656095', ratio: '9/16' },
    ],
  },
  'beats-by-dre-disney': {
    tags: ['motion', 'design'],
    categoryLabel: 'Concept / Sizzle',
    title: 'Beats by Dre\n× Disney',
    deliverable: 'Internal Proof of Concept',
    challenge: 'Build an internal sizzle reel merging Beats\' signature design language with Disney\'s iconic brand — enough to sell the concept to stakeholders.',
    solution: 'Designed and animated a concept piece that found the intersection between the two brands: bold, premium, and unmistakably fun.',
    logic: 'Proof-of-concept work lives or dies on how clearly it communicates potential. The reel needed to make the partnership feel inevitable.',
    color: '#1A3270',
    videos: [
      { id: '432654184', ratio: '16/9' },
    ],
  },

  'anchorman-2': {
    tags: ['design', 'motion'],
    categoryLabel: 'Title Design',
    title: 'Anchorman 2',
    deliverable: 'Opening Sequence Pitch',
    challenge: 'Pitch an opening sequence concept for Anchorman 2 that blended retro aesthetics with the film\'s comedic sensibility and classic news broadcasting references.',
    solution: 'Developed 15 style frames using a posterized, graphic treatment in Photoshop, Illustrator, C4D, and After Effects — capturing the satirical tone through bold typography and period-appropriate design.',
    logic: 'The concept was never produced, but the process of translating a film\'s comedic voice into a visual system is the same whether it ships or not.',
    color: '#8B1A1A',
    images: Array.from({length: 15}, (_, i) => `images/anchorman-2/frame-${i+1}.jpg`),
  },
  'barbie': {
    tags: ['motion', '3d'],
    categoryLabel: 'Music Video',
    title: 'Barbie',
    deliverable: 'Online Lyric Video',
    challenge: 'Create an online lyric video for Barbie\'s "Anything is Possible" with a stop-motion photography aesthetic and photo-realistic look.',
    solution: 'At Picture Mill, built C4D animation, lighting, and rendering to achieve the tactile, hand-crafted feel. Compositing by Nelson Yu.',
    logic: 'The challenge with photo-realistic CG is making it feel intentionally handmade — the stop-motion reference gave the project a warmth that pure CG rarely achieves.',
    color: '#E91E8C',
    images: [
      'images/barbie/frame-1.jpg',
      'images/barbie/frame-2.jpg',
    ],
    videos: [
      { id: '114088198', ratio: '16/9' },
    ],
  },
  'blackbox': {
    tags: ['motion', 'design'],
    categoryLabel: 'Title Design',
    title: 'Black Box',
    deliverable: 'Main Title Sequence Pitch',
    challenge: 'Design a main title sequence for a TV show about a respected doctor treating patients with mental illness — capturing the complexity of a multifaceted personality.',
    solution: 'Used reflective faceted panels as the core design motif, creating a visual metaphor for fragmented identity. Pitch was not produced. Studio: Picture Mill.',
    logic: 'Rejected pitches are still full design problems. The reflective panel system solved the brief — the production decision had nothing to do with the concept.',
    color: '#1C1C2E',
    images: [
      'images/blackbox/frame-1.jpg',
      'images/blackbox/frame-2.jpg',
      'images/blackbox/frame-3.jpg',
      'images/blackbox/frame-4.jpg',
      'images/blackbox/frame-5.jpg',
      'images/blackbox/frame-6.jpg',
      'images/blackbox/frame-7.jpg',
    ],
  },
  'san-francisco-49ers': {
    tags: ['motion', 'design'],
    categoryLabel: 'Broadcast Design',
    title: 'San Francisco 49ers',
    deliverable: 'Proof of Concept',
    challenge: 'Create a visual starting point for client discussions — something concrete enough to spark a conversation about what a full design engagement could look like.',
    solution: 'Developed a proof of concept at Picture Mill that established tone, motion language, and visual direction without overcommitting to a finished system.',
    logic: 'Proof-of-concept work is about demonstrating possibility, not delivering a product. The goal is to make a client see something they didn\'t know they wanted.',
    color: '#AA0000',
    images: [
      'images/san-francisco-49ers/frame-1.jpg',
    ],
  },
  'mom': {
    tags: ['motion', 'design'],
    categoryLabel: 'Title Design',
    title: 'Mom',
    deliverable: 'Main Title Sequence Pitch',
    challenge: 'Pitch a main title sequence for the TV show Mom — a comedy about addiction and family. Two distinct concept series: Wall and Fall.',
    solution: 'Wall explored found objects and domestic textures arranged as typographic elements. Fall used kinetic dropping motion to convey both comedy and consequence. Developed at Picture Mill.',
    logic: 'Comedy title sequences have to establish tone without undercutting the show\'s emotional honesty. Both concepts worked in opposite directions — one grounded, one kinetic.',
    color: '#C47A3A',
    images: Array.from({length: 11}, (_, i) => `images/mom/frame-${i+1}.jpg`),
  },
  'teenage-mutant-ninja-turtles': {
    tags: ['motion', 'design'],
    categoryLabel: 'Title Design',
    title: 'Teenage Mutant\nNinja Turtles',
    deliverable: 'Opening Sequence Pitch',
    challenge: 'Pitch an opening sequence concept for the TMNT film that captured the franchise\'s iconic energy while feeling modern enough for a feature film audience.',
    solution: 'Developed 18 style frames building a graphic, high-contrast visual system. Designed and animated at Picture Mill.',
    logic: 'Franchise IP comes with deep audience expectations. The design had to honor the source material while pushing it somewhere new — familiar but not nostalgic.',
    color: '#2D6B2D',
    images: Array.from({length: 18}, (_, i) => `images/teenage-mutant-ninja-turtles/frame-${i+1}.jpg`),
  },
  'ratpac': {
    tags: ['motion', 'design'],
    categoryLabel: 'Title Design',
    title: 'Ratpac\nEntertainment',
    deliverable: 'Logo Animation Concepts',
    challenge: 'Develop multiple logo animation concepts for Ratpac Entertainment — each with a distinct visual approach across three concept series: Chip, Dice, and Marquee.',
    solution: 'Created 16 style frames across the three series, each exploring different motion logic and visual texture to show range before committing to a direction.',
    logic: 'Logo animation pitches work best when they show a spread of directions rather than one polished answer. Three distinct concepts let the client find their instinct.',
    color: '#1A1A3A',
    images: Array.from({length: 16}, (_, i) => `images/ratpac/frame-${i+1}.jpg`),
  },
  'audi-imagination': {
    tags: ['design', 'motion'],
    categoryLabel: 'Style Frames',
    title: 'Audi\nImagination',
    deliverable: 'Broadcast Style Frames',
    challenge: 'Create style frames for an Audi A7 Sportback broadcast commercial for BBH London — a stylized journey through the mind of an automotive designer.',
    solution: 'Developed organic and mechanical imagery that blended the natural world with precision engineering. The designer\'s horse artwork was selected for the final version. Directed by Vanessa Marzaroli.',
    logic: 'Automotive design inspiration lives at the intersection of nature and engineering. The brief asked for that tension to be visualized — the horse became the answer.',
    color: '#1A1A1A',
    images: [
      'images/audi-imagination/frame-1.jpg',
      'images/audi-imagination/frame-2.jpg',
    ],
  },

  'walkman': {
    tags: ['design'],
    categoryLabel: 'Design',
    title: 'Walkman',
    deliverable: 'Nonprofit Design & Social Rebrand',
    challenge: 'Two projects for the National MS Society: design a benefit t-shirt for the Walk MS event, and rebrand the Emerging Leaders Board Instagram presence.',
    solution: 'Collaborated with illustrator Corey Jennings to translate artwork into a wearable vector design for Walk MS. For the IG rebrand, developed multiple template layouts exploring color, type, and visual direction.',
    logic: 'Nonprofit design has to work on a budget and at scale. The shirt design needed to hold up in production; the IG templates needed to be easy for the team to execute without a designer.',
    color: '#5B2D8E',
    images: Array.from({length: 7}, (_, i) => `images/walkman/frame-${i+1}.jpg`),
  },
  'skycoin': {
    tags: ['3d', 'design'],
    categoryLabel: '3D Design',
    title: 'Skywire\nMesh Internet',
    deliverable: 'Art Direction & 3D Design',
    challenge: 'Visualize a decentralized mesh internet network in a way that feels credible, technical, and aspirational.',
    solution: 'Art direction by Michael Malowanczyk. 3D design and rendering by Eric Zunkley and Michael Malowanczyk — building abstract network visualizations that communicated scale and connectivity.',
    logic: 'Technology visualization has to balance accuracy with accessibility. The work needed to feel like infrastructure, not decoration.',
    color: '#0D3B6E',
    images: [
      'images/skycoin/frame-1.jpg',
      'images/skycoin/frame-2.jpg',
    ],
  },
  'black-ops-4-anthem': {
    tags: ['motion'],
    categoryLabel: 'Broadcast',
    title: 'Black Ops 4\nAnthem',
    deliverable: 'Anthem Spot — Animation & Compositing',
    challenge: 'Design and animate sequences for the Call of Duty: Black Ops 4 anthem spot featuring music by Diplo and French Montana feat. Lil Pump.',
    solution: 'Handled animation, design, and compositing at Space 150 in collaboration with The Mill LA — working within a fast-moving production to deliver broadcast-ready motion.',
    logic: 'Anthem spots for major game releases demand precision under pressure. Every frame is scrutinized. The Mill\'s production standards set the bar; the job was to meet it.',
    color: '#1A1A1A',
  },
  'parkway-drive-boneyards': {
    tags: ['motion'],
    categoryLabel: 'Music Video',
    title: 'Parkway Drive\nBoneyards',
    deliverable: 'Music Video',
    challenge: 'Capture the raw intensity of Parkway Drive\'s live performance energy in a music video that matches the relentless pace of the song.',
    solution: 'Dynamic camera work and frenetic editing synced to the song\'s rhythm. Thematic references to the lyrics layered with stock footage for atmospheric depth. DP: Alex Gvojic, Editor: Dan Dobi. Client: Epitaph Records.',
    logic: 'Metal music video direction is about energy management — building and releasing tension in sync with the music. The cut has to feel inevitable.',
    color: '#2A1A0E',
    videos: [
      { id: '9212257', ratio: '16/9' },
    ],
  },

  'a-little-flexibility': {
    tags: ['design', 'motion'],
    title: 'A Little Flexibility\nOr A Lot',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Frow itself, let it be sorrow; let him love it; let him pursue it.',
    color: '#ad2c1c',
  },
  'in-motion': {
    tags: ['motion'],
    title: 'In Motion',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Every frame is a decision. This project explores the space between stillness and movement.',
    color: '#d35b2c',
  },
  'depth-study': {
    tags: ['3d', 'motion'],
    title: 'Depth Study',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Light, shadow, and material render what the eye expects the hand to feel.',
    color: '#1d5091',
  },
  'product-zero': {
    tags: ['product', 'design'],
    title: 'Product Zero',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Before the interface, before the brand — the object itself.',
    color: '#1d6f31',
  },
};
