var PROJECTS = {
  'ethos': {
    tags: ['design', 'motion'],
    categoryLabel: 'Design',
    title: 'Ethos',
    deliverable: 'Performance Marketing Concepts',
    challenge: 'Create performance marketing assets for life insurance on social — a category most people actively avoid thinking about — that stop the scroll and drive action.',
    solution: 'Three static concepts targeting different buyer objections: Price Over Time (cost urgency), Fixed Cost Q&A (rate certainty), and Seamless Online Access (frictionless sign-up).',
    logic: 'Each concept anchors to a distinct reason-to-buy without overlapping. Together they give media buyers options to test against different audience segments.',
    imageNote: '* Images are for reference only and used as a proof of concept. Photos sourced from jakestangel.com',
    motionSection: {
      intro: 'I designed and animated two motion concepts for Ethos\' performance marketing efforts.',
      concepts: [
        {
          title: 'Bouncing Coins — Affordability Message',
          body: 'This concept uses dynamic motion to engage viewers with real-world physics. Four quarters bounce around the screen, reinforcing the affordability of Ethos term life insurance, which costs less than $1 a day. The movement builds curiosity and keeps attention on the message.',
        },
        {
          title: 'UGC Story — Breaking the Taboo',
          body: 'This piece repurposes user-generated content to create a narrative around overcoming discomfort in discussing life insurance. The animation enhances the creator\'s message, making the topic more approachable and encouraging open conversations.',
        },
      ],
    },
    shortDescription: 'Performance marketing concepts for Ethos life insurance — static design and motion.',
    color: '#2c5f3f',
    images: [
      'images/ethos/frame-1.jpg',
      'images/ethos/frame-2.jpg',
      'images/ethos/frame-3.jpg',
      'images/ethos/frame-4.jpg',
    ],
    videos: [
      { id: '1069408293', title: 'Ethos — Bouncing Coins', ratio: '4/5' },
      { id: '1069408320', title: 'UGC — Taboo Topic', ratio: '4/5' },
      { id: '1069408280', title: 'Ethos — Concept', ratio: '9/16' },
      { id: '1069408307', title: 'UGC — Taboo Topic (Alt)', ratio: '9/16' },
    ],
  },
  'a-little-flexibility': {
    tags: ['design', 'motion'],
    title: 'A Little Flexibility\nOr A Lot',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Frow itself, let it be sorrow; let him love it; let him pursue it.',
    color: '#ad2c1c',
  },
  'in-motion': {
    tags: ['motion'],
    title: 'In Motion',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Every frame is a decision. This project explores the space between stillness and movement.',
    color: '#d35b2c',
  },
  'depth-study': {
    tags: ['3d', 'motion'],
    title: 'Depth Study',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Light, shadow, and material render what the eye expects the hand to feel.',
    color: '#1d5091',
  },
  'product-zero': {
    tags: ['product', 'design'],
    title: 'Product Zero',
    deliverable: 'Deliverable TBD',
    challenge: 'Challenge TBD',
    solution: 'Solution TBD',
    logic: 'Logic TBD',
    shortDescription: 'Before the interface, before the brand — the object itself.',
    color: '#1d6f31',
  },
};
